name: Coverity Scan
on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

  workflow_dispatch:

jobs:
  daily_scan:
    name: Daily Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
         gradle-version: "9.2.1"

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/java/linux64 --post-data "token=$TOKEN&project=Zialus%2FLP-mED" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_TOKEN }}

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int gradle build --no-daemon

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf snake.tgz cov-int
          curl \
          --form token=$TOKEN \
          --form email=raulmendesferreira@gmail.com \
          --form file=@snake.tgz \
          --form version="trunk" \
          --form description="LP-mED" \
          https://scan.coverity.com/builds?project=Zialus%2FLP-mED
        env:
          TOKEN: ${{ secrets.COVERITY_TOKEN }}
